
func nestedException1 () {
  nestedException2 ();
  println ("This should not print");
}

func nestedException2 () {
  raise "A nested exception";
  println ("This should not print");
}

try {
  println ("From try");
  raise "some exception";
  println ("should not print");
} catch (e) {
  println ("Caught: ");
  println (e);
}

try {
  nestedException1();
} catch (e) {
  println ("Caught ");
  println (e);
}